.TH LOOLWSD-GENERATE_PROOF_KEY "1" "April 2020" "modaodfweb-generate-proof-key " "User Commands"
.SH NAME
modaodfweb-generate-proof-key
.SH SYNOPSYS
modaodfweb-generate-proof-key
.SH DESCRIPTION
modaodfweb-generate-proof-key creates an RSA key pair in /etc/modaodfweb for the WOPI Proof headers. The script is automatically run by the postinstall script of modaodfweb package, but in case of failure sysadmins can run it manually.
.SH "SEE ALSO"
modaodfwebforkit(1), modaodfwebconvert(1), modaodfwebconfig(1), modaodfweb(1), modaodfweb-systemplate-setup(1)
