.TH MODAODFWEBCONVERT "1" "May 2018" "modaodfwebconvert" "User Commands"
.SH NAME
oxoolconvert \- MODA ODF WEB document converter tool
.SH SYNOPSIS
oxoolconvert OPTIONS FILE(S)
.SH OPTIONS
\fB\-\-help\fR                  Display help information on command line arguments.
.PP
\fB\-\-extension\fR=\fIformat\fR      file format extension to convert to
.PP
\fB\-\-outdir\fR=\fIoutdir\fR         output directory for converted files
.PP
\fB\-\-parallelism\fR=\fIthreads\fR   number of simultaneous threads to use
.PP
\fB\-\-server\fR=\fIuri\fR            URI of MODA ODF WEB server
.PP
\fB\-\-no\-check\-certificate\fR  Disable checking of SSL certs
.PP
.SH "SEE ALSO"
modaodfweb(1), modaodfwebforkit(1), modaodfwebconfig(1), modaodfweb-systemplate-setup(1), modaodfwebmount(1)
