.TH LOOLFORKIT "1" "May 2018" "modaodfwebforkit " "User Commands"
.SH NAME
modaodfwebforkit
.SH SYNOPSYS
modaodfwebforkit OPTIONS
.SH DESCRIPTION
Single-threaded process that spawns OxOffice Online Kit (LOK) instances.
.PP
\fBNote\fR: Running this standalone is not possible. It is spawned by modaodfweb and is controlled via a pipe.
.SH "SEE ALSO"
modaodfweb(1), modaodfwebconvert(1), modaodfwebconfig(1), modaodfwebforkit-systemplate-setup(1), modaodfweb-generate-proof-key(1)
