.TH LOOLFORKIT "1" "May 2018" "ndcodfwebforkit " "User Commands"
.SH NAME
ndcodfwebforkit
.SH SYNOPSYS
ndcodfwebforkit OPTIONS
.SH DESCRIPTION
Single-threaded process that spawns OxOffice Online Kit (LOK) instances.
.PP
\fBNote\fR: Running this standalone is not possible. It is spawned by ndcodfweb and is controlled via a pipe.
.SH "SEE ALSO"
ndcodfweb(1), ndcodfwebconvert(1), ndcodfwebconfig(1), ndcodfwebforkit-systemplate-setup(1), ndcodfweb-generate-proof-key(1)
