.TH LOOLWSD-GENERATE_PROOF_KEY "1" "April 2020" "ndcodfweb-generate-proof-key " "User Commands"
.SH NAME
ndcodfweb-generate-proof-key
.SH SYNOPSYS
ndcodfweb-generate-proof-key
.SH DESCRIPTION
ndcodfweb-generate-proof-key creates an RSA key pair in /etc/ndcodfweb for the WOPI Proof headers. The script is automatically run by the postinstall script of ndcodfweb package, but in case of failure sysadmins can run it manually.
.SH "SEE ALSO"
ndcodfwebforkit(1), ndcodfwebconvert(1), ndcodfwebconfig(1), ndcodfweb(1), ndcodfweb-systemplate-setup(1)
