.TH LOOLWSD-SYSTEMPLATE-SETUP "1" "May 2018" "ndcodfweb-systemplate-setup " "User Commands"
.SH NAME
ndcodfweb-systemplate-setup
.SH SYNOPSYS
ndcodfweb-systemplate-setup <chroot template directory for system libs to create> <NDCODFSYS installation directory>
.SH DESCRIPTION
ndcodfweb-systemplate-setup creates a minimal system template for running the LibreOfficeKit in a chroot jail. The system template contains the bare minimum of system libraries to run OxOfficeKit, and also fonts and locale data from the system.
.SH "SEE ALSO"
ndcodfwebforkit(1), ndcodfwebconvert(1), ndcodfwebconfig(1), ndcodfweb(1), ndcodfweb-generate-proof-key(1)
